### ISSUE TITLE
Build failed: Cannot read properties of undefined (reading 'mode')

### ISSUE THREAD

**Issue by jools-r** [gxy5202/parcel-namer-hashless#12]
If I just include `"namers": [ "parcel-namer-hashless" ],` as part of the `"extends": "@parcel/config-default",` block in `.parcelrc` (I have a few other reporters and resolvers in there too but no other namers) and nothing in `package.json`, then I get the following error on `pnpm build`:

```
🚨 Build failed.

parcel-namer-hashless: Cannot read properties of undefined (reading 'mode')

  TypeError: Cannot read properties of undefined (reading 'mode')
      at 
  /path/to/node_modules/.pnpm/parcel-namer-hashless@1.0.6_@parcel+core@2.11.0/node_modules/parcel-namer-hashless/lib/index.js:1:1859
      at step (/path/to/node_modules/.pnpm/tslib@2.6.2/node_modules/tslib/tslib.js:195:27)
      at Object.next (/path/to/node_modules/.pnpm/tslib@2.6.2/node_modules/tslib/tslib.js:176:57)
      at asyncGeneratorStep 
  (/path/to/node_modules/.pnpm/@swc+helpers@0.5.6/node_modules/@swc/helpers/cjs/_async_to_generator.cjs:5:28)
      at _next 
  (/path/to/node_modules/.pnpm/@swc+helpers@0.5.6/node_modules/@swc/helpers/cjs/_async_to_generator.cjs:23:17)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

 ELIFECYCLE  Command failed with exit code 1.
```

If I add the following to `package.json`, the build executes successfully

```
    "parcel-namer-hashless": {
        "mode": "all"
    },
```

The instructions say, however, this block is optional if you want to remove/omit the hashes from everything.

Is this a misconfiguration at my end or a does the lack of a mode setting need trapping in the plugin?

**Comment by gxy5202** [comment]
Thanks for your bug report. I will test it in these days.

**Comment by aminomancer** [comment]
I encountered the same thing, and resolved it the same way, by adding

```json
"parcel-namer-hashless": {}
```

**Comment by gxy5202** [comment]
> 我遇到了同样的事情，并以同样的方式解决了它，通过添加
> 
> ```json
> "parcel-namer-hashless": {}
> ```

I think this is an uncaught bug, because i don't give it a value by default.

**Comment by aminomancer** [comment]
> Can you give an example of how to use the workaround in your .parcelrc file? I'm getting the error too, but this is a syntax error:
> 
> ```
> "namers": [
>     "parcel-namer-hashless": {}
>  ]
> ```

I meant adding it to package.json, not to .parcelrc.
